# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:3

definitions:
  verify-iam-pipe: &verify-iam-pipe 
    name: Run IAM testing image
    image: postnord/iam-pipe
    script: 
      - /app/run-pipes.sh

pipelines:
  pull-requests:
    "**":
      - step: *verify-iam-pipe

  branches:
    master:
      - parallel:
          - step: *verify-iam-pipe
          - step:
              name: Docker build and push
              oidc: true
              caches:
                - docker
              services:
                - docker
              script:
                # build the image
                - docker build --build-arg NPM_TOKEN=${NPM_TOKEN} --build-arg RELEASE=${BITBUCKET_BUILD_NUMBER} -t $IMAGE_NAME .
                # use the pipe to push to AWS ECR
                - pipe: atlassian/aws-ecr-push-image:1.3.0
                  variables:
                    AWS_OIDC_ROLE_ARN: $AWS_OIDC_ROLE_ARN
                    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                    IMAGE_NAME: $IMAGE_NAME
                    TAGS: "'${BITBUCKET_BUILD_NUMBER}'"
                # use pipe to update sentry release number
                - pipe: docker://postnord/sentry-release:latest
                  variables:
                    SENTRY_AUTH_TOKEN: $SENTRY_AUTH_TOKEN
                    SENTRY_ORG: $SENTRY_ORG
                    SENTRY_PROJECT: $SENTRY_PROJECT
                    BUILD_NUMBER: ${BITBUCKET_BUILD_NUMBER}
          - step:
              name: Dependency-Track upload
              image: node:16.13.2
              script:
                - npm ci
                - node_modules/.bin/cyclonedx-bom -o bom.xml --include-dev
                - pipe: docker://pndigital/dependency-track-upload:1.0
                  variables:
                    PROJECT_NAME: "iam-$IMAGE_NAME"
                    PROJECT_VERSION: ${BITBUCKET_BUILD_NUMBER}
                    DEPENDENCY_TRACK_URL: $DEPENDENCY_TRACK_URL
                    BOM_FILE: "bom.xml"
                    X_API_KEY: $DEPENDENCY_TRACK_APIKEY
                    # DEBUG: "true" # Optional
